### PR TITLE
Updated to add new features, better document some things, and prevent misconfigurations

### PR DESCRIPTION
**Pull request by facklambda**
The [fly.toml](fly.toml) updates include

- Comments w/ explanations
- SMTP setup
- S3-like Object Storage setup
- Streaming API setup
- Streaming API healthchecks
- modified port numbers to be inline with default mastodon port choices.

The [fly.redis.toml](fly.redis.toml) update includes:

- Comments explaining why changes are needed

The [README.md](README.md) updates include:

- Expanded documentation
- Links to files, and external reference documentation
- Fixes to commands that failed to run correctly

### CODE REVIEW

**Comment by tmm1** [comment]
Thanks but I'm afraid this will conflict with #2. Some of the issues are already being addressed there

cc @indirect

**Comment by facklambda** [comment]
I'm afraid I didn't see that PR when I began work on it!

**Comment by indirect** [comment]
Thanks for pointing out the possible issue with `fly secrets import`! I added a `sed 's/\r//'` to hopefully take care of that, it looks like some outputs use `\r\n` but `fly secrets import` only splits on `\n` and then the secrets end up containing the trailing `\r`. Probably worth filing a bug against `flyctl` about that.

Hopefully everything else you mention is taken care of by my PR, but I'm happy to hear suggestions you might have over there.

**Comment by facklambda** [comment]
No worries, I'll take a look at submitting that to fly.

I think there's a deep difference between the routes we went with our architecture here. I built on fly's nomad based platform and it looks like you went with their newer "machines" based platform.

I'll offer that mine is just one step above the free tier as far as cost goes, I'm curious how much it costs to run on the machines platform. But I suspect this is just an apples to oranges comparison since your architecture seems to be significantly more scalable.

**Comment by indirect** [comment]
For whatever it’s worth, my changes also offer a cheaper “smallest” option, going as low as a single shared-cpu core with 1GB, and one 3GB volume, which is iirc exactly the free allowance. That’s probably not sustainable in the long run, as following people creates a lot of cached images, but it does mean you can scale rails and sidekiq up separately as needed.

**Comment by facklambda** [comment]
I'm probably gonna close this PR.

It also looks like https://github.com/superfly/flyctl/issues/996 has been reported already.

Thanks all!

**Pull request closed without merging**
