### PR TITLE
Update for new flyctl, add instructions, fix media volume

### LINKED ISSUE #1: Sidekiq and Puma can't run in separate processes/VMs
Mastodon contains a feature that creates a background job to retry if fetching remote media fails: https://github.com/mastodon/mastodon/pull/11775.

Unfortunately, since Fly cannot mount the same volume in different process VMs, that means Sidekiq creates a valid database record and then writes the image into a container-only temporary file system. At that point Mastodon starts returning 404s for those images, but it has a valid DB record, so there's not any easy way to recover.

I think this means that Puma and Sidekiq have to run inside the same VM for this to work at all.

### PR DESCRIPTION
**Pull request by indirect**
This set of changes updates the steps for the changes to `flyctl` options since the guide was originally written.

It also uses Overmind to run both Rails and Sidekiq inside the same VM, so they can share the volume with cached media. Without sharing a volume, network errors generate background jobs to try again later, and Sidekiq downloads the media into a container that the web server can't get to, causing random broken image tags.

Also added some notes about setting up SMTP, as well as upgrading Mastodon, and using custom domains with SSL.

Fixes #1.

### CODE REVIEW

**Comment by tmm1** [comment]
> Without sharing a volume, network errors generate background jobs to try again later, and Sidekiq downloads the media into a container that the web server can't get to, causing random broken image tags.

Ah, interesting. This is when you're not using S3 etc for attachments?

**Comment by indirect** [comment]
Yes, if you use Fly volumes to hold the fetched remote media, the files downloaded by Sidekiq become random 404s. On Fly, volumes are 1-1 with VMs.

**Comment by tmm1** [comment]
Gotcha. Thanks for working on this!

I just remembered I think there's one more piece missing, the streaming nodejs server.

IIRC, you have to run the nginx inside docker too and tell it to send `/api/v1/streaming` requests to the nodejs server. We'll have to add the nodejs streaming entry to the Procfile as well.

See https://github.com/jesseplusplus/decodon/pull/7

**Comment by indirect** [comment]
Thanks for calling that out, I added the node streaming server to the Procfile and added Caddy to reverse proxy just the one URL.

**Comment by tmm1** [comment]
Awesome, this is looking great.

Re: #1, since the issue there is specific to local assets.. it'd be nice to still allow separate sidekiq workers that can be scaled up separately from the web app. Maybe we can document the choices in the readme? So if you choose to store assets locally then you have to run in the combined mode, otherwise you can separate them via env vars or something?

I would guess most mastodon instances are using s3 or other cloud storage. It might make sense to make that the default here too, so you're not stuck with a single puma/sidekiq if you need to scale?

**Comment by indirect** [comment]
Yeah, I think that's probably true. Part of the reason I removed the `[processes]` directive is that it's a little half-baked--you can never remove process groups once they've been created, and VMs seem to stop correctly associating with regions. In my original testing, Sidekiq kept starting up in a random far-away region, even when it was supposedly only allowed to use the same region as the redis and web servers.

Let me think about how to implement an option or transition plan and get back to you later today or tomorrow.

**Comment by indirect** [comment]
Okay, I think I've figured out a reasonable plan that includes a way to transition from volumes to cloud storage, and from all-in-one to "web" and "sidekiq" apps that can scale their count separately. You can even keep image URLs identical via Caddy, if you want that. I've tested this out on my own instance, migrating from a Fly Volume to Wasabi (which is API-identical to S3), and then migrating the sidekiq worker out into a separate app so it can scale on its own.

However, Mastodon seems very shouty about how you must never run more than one sidekiq process with the `scheduler` job, and it's not at all clear to me how to scale a sidekiq process or app while keeping that true. I would love to hear how you have solved this elsewhere.

**Comment by indirect** [comment]
After a bunch more fiddling, I think `[processes]` actually is the way to go for separately scalable worker processes that share env vars and secrets, we just have to be sure to only ever have one process running the `schedule` queue. I've updated the readme and the fly.toml file to have pre-written sections that you can uncomment to have horizontally scalable Rails and non-schedule-queue Sidekiq VMs.

**Comment by tmm1** [comment]
cc @jsierles @tqbf

**Pull request merged**
